[package]
name = "anonvote_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
zkp_protocol = { path = "../zkp_protocol" }
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]
